spring:
  profiles:
    active: dev
  application:
    name: deer-platform
        
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  # 静态资源配置
  web:
    resources:
      static-locations: file:frontend/,file:uploads/
      
server:
  port: 8080
  servlet:
    context-path: /api
    
# JWT配置
jwt:
  secret: deerPlatformSecretKey2024ForJWTTokenGeneration
  expiration: 86400000  # 24小时

# 文件上传路径配置
file:
  upload:
    path: uploads/
    avatar-path: uploads/avatars/
    post-images-path: uploads/post-images/
    max-size: 10485760