spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deer_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: deeruser
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  # 邮件配置
  mail:
    host: smtp.163.com  # QQ邮箱SMTP服务器
    port: 25
    username: muskdeerplatform@163.com  
    password: URZZd97GPpkHKnTe  # 请替换为您的QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false  # 163邮箱25端口不强制TLS
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
        
  # SQL初始化配置
  sql:
    init:
      mode: never

# 日志配置
logging:
  level:
    com.deerplatform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  file:
    "upload-dir": "uploads/dev/"  # 使用引号包围
    
# 文件上传路径配置
file:
  upload:
    path: ./uploads
    avatar-path: ./uploads/avatars
    post-images-path: ./uploads/post-images